training:
  id: "helimos_hard"
  train:
    - "Velodyne/train.txt"
    - "Avia/train.txt"
  val:
    - "Ouster/val.txt"
    - "Aeva/val.txt"
    - "Velodyne/val.txt"
    - "Avia/val.txt"

# Ouster : Super-Dense, 128, 360(circular pattern), 고용량
# Velodyne : Sparse, 16, 360(circular pattern), 저용량
# Aeva : Dense, null, wide(circular pattern), 고용량
# Avia(Livox) : Dense, null, narrow(flower pattern), 저용량